# 01 EDA & Feature Engineering: College Football Attendance

## Import libraries and the datasets

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

RAW_DATA_DIR = Path("../data/raw")

games_df = pd.read_csv(RAW_DATA_DIR / "cfbd_games_2023_2025.csv")
fbs_stadiums_df = pd.read_csv(RAW_DATA_DIR / "fbs-stadiums-original.csv")
fcs_stadiums_df = pd.read_csv(RAW_DATA_DIR / "fcs-stadiums-original.csv")
geocoded_stad_df = pd.read_csv(RAW_DATA_DIR / "stadiums-geocoded.csv")

### Make sure that datasets are loaded

In [2]:
games_df.head()

,id,season,week,seasonType,startDate,startTimeTBD,completed,neutralSite,conferenceGame,attendance,...,awayConference,awayPoints,awayLineScores,awayPostgameWinProbability,awayPregameElo,awayPostgameElo,excitementIndex,highlights,notes,playoff
0,401525434,2023,1,regular,2023-08-26T18:30:00.000Z,False,True,True,False,49000.0,...,American Athletic,3.0,"[0, 0, 0, 3]",0.023594,1471.0,1385.0,1.646466,NaN,NaN,NaN
1,401540199,2023,1,regular,2023-08-26T19:30:00.000Z,False,True,True,False,NaN,...,UAC,7.0,"[7, 0, 0, 0]",0.031442,NaN,NaN,4.165937,NaN,NaN,NaN
2,401520145,2023,1,regular,2023-08-26T21:30:00.000Z,False,True,False,True,17982.0,...,Conference USA,14.0,"[0, 7, 0, 7]",0.192517,1369.0,1370.0,4.604490,NaN,NaN,NaN
3,401525450,2023,1,regular,2023-08-26T23:00:00.000Z,False,True,False,False,15356.0,...,FBS Independents,41.0,"[7, 3, 3, 28]",0.882491,1074.0,1122.0,5.430058,NaN,NaN,NaN
4,401532392,2023,1,regular,2023-08-26T23:00:00.000Z,False,True,False,False,23867.0,...,Mid-American,13.0,"[3, 3, 0, 7]",0.121683,1482.0,1473.0,5.105937,NaN,NaN,NaN

In [3]:
fbs_stadiums_df.head()

,image,stadium,city,state,team,conference,capacity,built,expanded
0,Michigan Stadium 2011.jpg,Michigan Stadium,Ann Arbor,MI,Michigan,Big Ten,"107,601[98]",1927,2015
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Beaver Stadium inside.jpg,Beaver Stadium,University Park,PA,Penn State,Big Ten,"106,572[12]",1960,2001
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Ohio Stadium, Columbus.jpg",Ohio Stadium,Columbus,OH,Ohio State,Big Ten,"104,944[106]",1922[108],2014[108]

In [4]:
fcs_stadiums_df.head()

,image,stadium,city,state,team,conference,capacity,built,expanded
0,LP Field 2009 crop.jpg,LP Field,Nashville,Tennessee,Tennessee State Tigers,Ohio Valley,"68,798",1999,NaN
1,Yale bowl birds eye view.png,Yale Bowl,New Haven,Connecticut,Yale Bulldogs,Ivy,"61,446[106]",1914[106],NaN
2,Mississippi Veterans Memorial Stadium.jpg,Mississippi Veterans Memorial Stadium,Jackson,Mississippi,Jackson State Tigers,SWAC,"60,492",1941[69],NaN
3,Franklin Field aerial.jpg,Franklin Field,Philadelphia,Pennsylvania,Penn Quakers,Ivy,"52,593[37]",1895[37],NaN
4,Harvard Stadium aerial.jpg,Harvard Stadium,Boston,Massachusetts,Harvard Crimson,Ivy,"30,323[48]",1903[48],2007[48]

In [5]:
geocoded_stad_df.head()

,stadium,city,state,team,conference,capacity,built,expanded,div,latitude,longitude
0,Michigan Stadium,Ann Arbor,MI,Michigan,Big Ten,107601,1927,2015,fbs,42.265869,-83.748726
1,Beaver Stadium,University Park,PA,Penn State,Big Ten,106572,1960,2001,fbs,40.812153,-77.856202
2,Ohio Stadium,Columbus,OH,Ohio State,Big Ten,104944,1922,2014,fbs,40.001686,-83.019728
3,Kyle Field,College Station,TX,Texas A&M,SEC,102733,1927,2015,fbs,30.610098,-96.340729
4,Neyland Stadium,Knoxville,TN,Tennessee,SEC,102455,1921,2010,fbs,35.954734,-83.925333